name: clouddrift
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy>=1.21.6
  - xarray>=2023.5.0
  - netcdf4>=1.6.4
  - pyarrow>=9.0.0
  - tqdm>=4.64.1
  - fsspec>=2022.8.2
  - llvmlite>=0.38.1
  - awkward>=2.0.0
  - pip>=22.2.2
  - aiohttp>=3.8.4
  - requests>=2.31.0
  - zarr>=2.14.2
  - pip:
    - git+https://github.com/Cloud-Drift/clouddrift.git
