name: clouddrift
channels:
  - conda-forge
dependencies:
  - cartopy
  - dask
  - dask-labextension
  - erddapy
  - jupyterlab
  - matplotlib
  - numpy
  - netCDF4
  - pandas
  - xarray
  - pyarrow
  - numba
  - cfgrib
  - tqdm
  - pip
  - pip:
    -  git+https://github.com/scikit-hep/awkward.git@1.9.0rc4
