name: clouddrift
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy>=1.21.6
  - xarray>=2022.6.0
  - netcdf4>=1.6.1
  - pyarrow>=9.0.0
  - tqdm>=4.64.1
  - fsspec>=2022.8.2
  - llvmlite>=0.38.1
  - awkward>=2.0.0
  - pip>=22.2.2
  - pip:
    - git+https://github.com/Cloud-Drift/clouddrift.git
