name: clouddrift
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - matplotlib>=3.5.2
  - numpy>=1.22.4
  - pandas>=1.4.2
  - xarray>=2022.3.0
  - netcdf4>=1.5.8
  - pyarrow>=8.0.0
  - zarr>=2.11.3
  - numba>=0.53.1
  - tqdm>=4.64.0
  - fsspec>=2022.3.0
  - pip>=22.1.1
  - pip:
    - awkward>=1.9.0
    - clouddrift
